D:\ethereum\devnet\prysm\config.yml
docker run -it -v D:\ethereum\devnet\prysm\config.yml:config.yml gcr.io/prysmaticlabs/prysm/cmd/prysmctl:latest testnet generate-genesis --num-validators=64 --output-ssz=genesis.ssz --chain-config-file=config.yml --override-eth1data=true
