CONFIG_NAME: custom
PRESET_BASE: minimal

# Genesis
GENESIS_FORK_VERSION: 0x00000000

# Altair
ALTAIR_FORK_EPOCH: 0
ALTAIR_FORK_VERSION: 0x00000000

# Merge
BELLATRIX_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: 0x00000000
TERMINAL_TOTAL_DIFFICULTY: 0

# Capella
CAPELLA_FORK_VERSION: 0x00000000

# Time parameters
SECONDS_PER_SLOT: 12
SLOTS_PER_EPOCH: 6

# Deposit contract
DEPOSIT_CONTRACT_ADDRESS: 0x123463a4b065722e99115d6c222f267d9cabb524
